const express = require('express')
const router = express.Router()
const CourseController = require('../app/Controllers/CourseController')
router.get('/create-course', CourseController.createCourse)
router.post('/store', CourseController.store)
router.get('/trash', CourseController.trash)
router.get('/:id/update-course',CourseController.viewUpdate)
router.delete('/:id/delete',CourseController.deleteCourse)
router.delete('/:id/force',CourseController.deleteForce)
router.patch('/:id/restore',CourseController.restore)
router.post('/handleSubmitCheckItems', CourseController.handleCheckItems)
router.post('/handleSubmit-CheckItems-InTrash', CourseController.handleCheckItemsInTrash)
router.put('/:id' , CourseController.edited)
router.get('/:slug', CourseController.show)
module.exports = router